<?php
// Copyright 1999-2017. Parallels IP Holdings GmbH.
?>
<script type="text/javascript">
    Jsw.onReady(function () {
        var select = document.getElementById('<?=$this->form->getElement('masterIp')->getId()?>');

        function updateMasterPublicIp() {
            var value = select.options[select.selectedIndex].text;
            var placeholders = document.getElementsByClassName('js-placeholder-ip');
            for (var i = 0; i < placeholders.length; i++) {
                placeholders[i].innerHTML = value;
            }
        }
        select.addEventListener('change', updateMasterPublicIp);

        var config = document.getElementById('slave-config');
        config.innerHTML = config.innerHTML.replace(/%%js-placeholder-ip%%/g, '<span class="js-placeholder-ip"></span>');
        updateMasterPublicIp();
    });
</script>
<div class="hint" id="slave-config">
    <?=$this->partial('index/slave-config.phtml', [
        'masterPublicIp' => '%%js-placeholder-ip%%',
        'secret' => $this->form->getElement('secret')->getValue(),
    ])?>
</div>
<p>
    <a href="https://www.plesk.com/blog/product-technology/slave-dns-and-plesk" target="_blank"><?php echo $this->lmsg('learnMore') ?></a>
</p>
<?php echo $this->form ?>
