<?php
// Copyright 1999-2016. Parallels IP Holdings GmbH.
?>
<div class="hint">
    <?php echo $this->partial('index/slave-config.phtml', array('pleskIp' => $this->pleskIp, 'secret' => $this->form->getElement('secret')->getValue())) ?>
</div>
<p>
    <a href="http://devblog.plesk.com/2013/10/slave-dns-and-plesk/" target="_blank"><?php echo $this->lmsg('learnMore') ?></a>
</p>
<?php echo $this->form ?>
