<ul class="ul">
    <li>Add to <i>named.conf</i> (config location depends on OS of slave server):<br>
        <pre>
        options {
            ...
            allow-new-zones yes;
        };

        controls {
            inet * port 953 allow { <b>&lt;PLESK_IP&gt;</b>; 127.0.0.1; };
        };
        </pre>
    </li>
    <li>Secret key you can get in <i>rndc.key</i> or <i>rndc.conf</i>, for example:<br>
        <pre>
        key &quot;rndc-key&quot; {
          algorithm hmac-md5;
          secret &quot;<b>vwOxonI4n4CVRUhKAOAAIA==</b>&quot;;
        };
        </pre>
    </li>
</ul>
<div class="btns-box">
    <span class="btn action" onclick="window.location.href='<?php echo $this->uplevelLink ?>'">
        <button type="button" value="" name="send">OK</button>
    </span>
</div>