<?php
// Copyright 1999-2016. Parallels IP Holdings GmbH.
?>
<?=pm_Locale::lmsg('howTo')?>:
<pre>
options {
    ...
    allow-new-zones yes;
};

    key &quot;rndc-key-<i><?=$this->escape($this->masterIp)?></i>&quot; {
  algorithm hmac-md5;
  secret &quot;<b><?=$this->escape($this->secret)?></b>&quot;;
};

controls {
    inet * port 953 allow { <b><?=$this->escape($this->masterIp)?></b>; 127.0.0.1; } keys { &quot;rndc-key-<i><?=$this->escape($this->masterIp)?></i>&quot;; };
};
</pre>
